### ISSUE TITLE
Actualizar Readme

### ISSUE THREAD

**Issue by JeremasPosta** [AleYanc/pipnd-client#1]
Es necesario escribir un Readme apropiado, con información para contribuir al proyecto y contenido relevante.

**Comment by AleYanc** [comment]
Trabajando en eso! El README ya está actualizado, y continuará creciendo a futuro!

**Comment by AleYanc** [comment]
> Vos sabés que salí del Issue y vi justo que lo habías actualizado. Saludos! 
> […](#)
Jajaja justo! Un saludo a vos también.
